---
project:
  output-dir: _output
  execute-dir: project
toc: true
number-sections: true
format:
  html:
    css: styles.css
    html-math-method: katex
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
